version: "3"
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: node-server
    restart: always
    ports:
      - 8081:8081
    # command: bash -c /usr/src/app/start.sh
    # env_file: .env
